### ISSUE TITLE
check-chef-client.rb missing

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-chef#1]
Please include the check-chef-client.rb script.

**Comment by mattyjones** [comment]
@runningman84  Is this script in the community-plugins-repo?  Where is it located?

**Comment by runningman84** [comment]
I haven't found the original source but this is a copy:
https://github.com/runningman84/chef-monitor/blob/f3fc1e61e2b54e29cb975fd38716518876573010/files/default/plugins/check-chef-client.rb
The code itself doesn't look very good, maybe we could change it to use the existig check-process.rb check.

**Comment by mattyjones** [comment]
I would think that would best upon a quick glance

**Comment by runningman84** [comment]
OK we can close this.
