### ISSUE TITLE
Cannot sign the request without a client name

### ISSUE THREAD

**Issue by jmreicha** [sensu-plugins/sensu-plugins-chef#13]
Here is the command I'm running:

```
./check-chef-nodes.rb -t 86400 -U https://api.opscode.com/organizations/<org> -K /etc/chef/<key>
```

I'm seeing the following error:

```
Check failed to run: Cannot sign the request without a client name, check that :node_name is assigned, ["/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http/auth_credentials.rb:40:in `signature_headers'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http/authenticator.rb:88:in `authentication_headers'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http/authenticator.rb:43:in `handle_request'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:217:in `block in apply_request_middleware'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:215:in `each'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:215:in `inject'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:215:in `apply_request_middleware'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/http.rb:139:in `request'", "/var/lib/gems/1.9.1/gems/chef-11.12.8/lib/chef/rest.rb:115:in `get'", "./check-chef-nodes.rb:73:in `nodes_last_seen'", "./check-chef-nodes.rb:103:in `any_node_stuck?'", "./check-chef-nodes.rb:86:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-0.3.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

I get a different error if I use the `-C` flag.

```
Check failed to run: undefined local variable or method `exclude_nodes' for #<ChefNodesStatusChecker:0x0000000296bd68>, ["./check-chef-nodes.rb:74:in `block in nodes_last_seen'", "./check-chef-nodes.rb:74:in `delete_if'", "./check-chef-nodes.rb:74:in `nodes_last_seen'", "./check-chef-nodes.rb:103:in `any_node_stuck?'", "./check-chef-nodes.rb:86:in `run'", "/var/lib/gems/1.9.1/gems/sensu-plugin-0.3.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

I suspect I'm missing a gem somewhere but maybe there is something else going on?

**Comment by jmreicha** [comment]
Using the `-C` flag and removing all references to `exclude_nodes` seems to fix it as a workaround..

**Comment by mattyjones** [comment]
@jmreicha Can you test/confirm this with a Ruby version >2.0 as support for <=1.9.3 is going to be dropped shortly. If this is still an issue we would be happy to take a look at it.

**Comment by rdrgmnzs** [comment]
I'm actually seeing this same issue with the embedded version of ruby that comes with sensu. 

Ruby: 2.3.0
Sensu: 0.25.3-1 
chef-server: 12.7.0-1

**Comment by majormoses** [comment]
@brdude what version of the gem are you using?

**Comment by itdevon** [comment]
I'm having the same issue. 
Here are the embedded sensu gems I'm using. 
 
chef (12.6.0, 11.18.12)
sensu (0.26.5)

**Comment by majormoses** [comment]
I am quite a bit behind on versions on this but I will try updating in the next few weeks (things are just a little crazy atm) and seeing if I can replicate. I think it might also be useful to see peoples full command they are running with options etc.

Here is mine taken from my cookbook:
`check-chef-nodes.rb -U #{Chef::Config[:chef_server_url]} -C :::chef.client.node|#{node.name}::: -K /etc/sensu/conf.d/chef-client.pem -t 1800` let me know if you see the same issue in your env with the pinned version at 0.4.0

**Comment by itdevon** [comment]
Here is mine.. 

 /etc/sensu/plugins/check-chef-nodes.rb -t 7200 -U https://www.domain.com -K /etc/chef/client.pem

**Comment by majormoses** [comment]
@Devon21 so you are not passing the client name which is required and the check does not have a default, what happens if you specify this? I think we need to look at either requiring the value or having a sensible default like the equivalent of `hostname --fqdn` or in ruby `Socket.gethostbyname(Socket.gethostname).first`

**Comment by eheydrick** [comment]
2.0.0 now requires a client name to be set.
