### ISSUE TITLE
error on check-chef-server

### ISSUE THREAD

**Issue by lcc2207** [sensu-plugins/sensu-plugins-chef#14]
I am seeing the following error 

Check failed to run: type mismatch: String given, ["/etc/sensu/plugins/check-chef-server.rb:47:in `=~'", "/etc/sensu/plugins/check-chef-server.rb:47:in`block in run'", "/etc/sensu/plugins/check-chef-server.rb:46:in `each_line'", "/etc/sensu/plugins/check-chef-server.rb:46:in`run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in class:CLI'"]

if I change this line
if proc =~ '^(fail|down|warning)'  **back to** if proc.match('^(fail|down|warning)') it seems to work ok.

**Comment by mattyjones** [comment]
@lcc2207 What version of Chef are you using?

**Comment by lcc2207** [comment]
Chef server 12.5 on Ubuntu.. Same result on Chef server 12.4 on CentOS

**Comment by mattyjones** [comment]
@tas50 Thoughts on this. I am looking into it as well.

**Comment by lcc2207** [comment]
This seems to work ok
if proc =~ /fail|down|warning/

**Comment by cwjohnston** [comment]
Looks like this was resolved in #15 which will go out in next release.
