### ISSUE TITLE
Proposal: change default critical time value to match default of 'chef-client' cookbook

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-chef#4]
I would imagine a lot of people commonly use the 'chef-client' cookbook to make sure that their chef-clients are converging on a regular interval. The default in the check is 1080 (18 minutes) while the default attribute while obviously changable is set to 1800 (30 minutes): https://github.com/opscode-cookbooks/chef-client/blob/master/attributes/default.rb#L39 I would think it make sense to set the default to be something more like 2100 (35 minutes) or 2400 (40 minutes). 

If this sounds like a good idea I would be more than happy to put together a PR

**Comment by majormoses** [comment]
@mattyjones @tas50 any thoughts? if you think this makes sense I will put together a PR

**Comment by eheydrick** [comment]
I think default > 30 makes sense given the 30 minute + 5 minute splay default in the chef-client cookbook.

**Comment by eheydrick** [comment]
Released in version [0.0.6](https://rubygems.org/gems/sensu-plugins-chef/versions/0.0.6).
